package com.example.editor.settings

import androidx.compose.runtime.staticCompositionLocalOf
import java.util.Locale

/**
 * Type-safe, instant-switch localization provider for Arabic and English.
 * Guarantees zero latency and instantaneous recomposition when changing languages.
 */
data class AppStrings(
    val appName: String,
    val settings: String,
    val editor: String,
    val appearance: String,
    val behavior: String,
    val uiLanguage: String,
    val theme: String,
    val fontSize: String,
    val tabSize: String,
    val wordWrap: String,
    val showLineNumbers: String,
    val highlightCurrentLine: String,
    val autoIndent: String,
    val autoCloseBrackets: String,
    val syntaxHighlighting: String,
    val autoSave: String,
    val autoSyncDisk: String,
    val autoSaveInterval: String,
    val explorer: String,
    val workspace: String,
    val recents: String,
    val newFile: String,
    val newFolder: String,
    val openFile: String,
    val folderTree: String,
    val createExternalDoc: String,
    val support: String,
    val runPreview: String,
    val formatCode: String,
    val saveFile: String,
    val save: String,
    val cancel: String,
    val systemLang: String,
    val englishLang: String,
    val arabicLang: String,
    val themeDark: String,
    val themeLight: String,
    val themeBlack: String,
    val themeSystem: String,
    val findPlaceholder: String,
    val replacePlaceholder: String,
    val replace: String,
    val replaceAll: String,
    val matchCase: String,
    val wholeWord: String,
    val regex: String,
    val previousMatch: String,
    val nextMatch: String,
    val closeSearch: String,
    val languagesFormatter: String,
    val searchLanguagePlaceholder: String,
    val renameFile: String,
    val deleteFile: String,
    val closeTab: String,
    val fileProperties: String,
    val goToLine: String,
    val shortcuts: String,
    val line: String,
    val col: String,
    val saved: String,
    val modified: String,
    val terminal: String,
    val console: String,
    val preview: String,
    val splitView: String,
    val clear: String,
    val executionCompleted: String,
    val executionError: String,
    val running: String,
    val inputPrompt: String,
    val sendInput: String
) {
    companion object {
        val English = AppStrings(
            appName = "CodeXCroc",
            settings = "Settings",
            editor = "Editor",
            appearance = "Appearance",
            behavior = "Behavior",
            uiLanguage = "UI Language",
            theme = "Theme",
            fontSize = "Font Size",
            tabSize = "Tab Size",
            wordWrap = "Word Wrap",
            showLineNumbers = "Show Line Numbers",
            highlightCurrentLine = "Highlight Active Line",
            autoIndent = "Auto-Indent",
            autoCloseBrackets = "Auto-Close Brackets",
            syntaxHighlighting = "Syntax Highlighting",
            autoSave = "Auto-Save to Local Storage",
            autoSyncDisk = "Auto-Sync Changes to File",
            autoSaveInterval = "Auto-Save Interval",
            explorer = "Explorer",
            workspace = "Workspace",
            recents = "Recents",
            newFile = "New File",
            newFolder = "New Folder",
            openFile = "Open File",
            folderTree = "Folder Tree",
            createExternalDoc = "External File (SAF)",
            support = "Support & Community",
            runPreview = "Run / Preview Code",
            formatCode = "Format Code",
            saveFile = "Save File",
            save = "Save",
            cancel = "Cancel",
            systemLang = "System Default",
            englishLang = "English",
            arabicLang = "العربية",
            themeDark = "Dark",
            themeLight = "Light",
            themeBlack = "Pitch Black (AMOLED)",
            themeSystem = "System",
            findPlaceholder = "Find...",
            replacePlaceholder = "Replace...",
            replace = "Replace",
            replaceAll = "All",
            matchCase = "Aa (Case)",
            wholeWord = "\\b (Word)",
            regex = ".* (Regex)",
            previousMatch = "Previous match",
            nextMatch = "Next match",
            closeSearch = "Close search",
            languagesFormatter = "Languages / Formatter",
            searchLanguagePlaceholder = "Search language or extension (e.g. Python, js)...",
            renameFile = "Rename File",
            deleteFile = "Delete File",
            closeTab = "Close Tab",
            fileProperties = "File Properties",
            goToLine = "Go to Line",
            shortcuts = "Keyboard Shortcuts",
            line = "Ln",
            col = "Col",
            saved = "Saved",
            modified = "Modified",
            terminal = "Terminal",
            console = "Console",
            preview = "Preview",
            splitView = "Split View",
            clear = "Clear",
            executionCompleted = "Completed (0)",
            executionError = "Error (1)",
            running = "Running...",
            inputPrompt = "Enter input...",
            sendInput = "Send"
        )

        val Arabic = AppStrings(
            appName = "CodeXCroc",
            settings = "الإعدادات",
            editor = "المحرر",
            appearance = "المظهر",
            behavior = "السلوك",
            uiLanguage = "لغة الواجهة",
            theme = "السمة واللون",
            fontSize = "حجم الخط",
            tabSize = "مسافة التاب (Tab)",
            wordWrap = "التفاف الأسطر",
            showLineNumbers = "إظهار أرقام الأسطر",
            highlightCurrentLine = "تمييز السطر النشط",
            autoIndent = "إزاحة تلقائية",
            autoCloseBrackets = "إغلاق الأقواس تلقائياً",
            syntaxHighlighting = "تلوين الصيغة البرمجية",
            autoSave = "الحفظ التلقائي في الذاكرة",
            autoSyncDisk = "مزامنة التغييرات مع الملف",
            autoSaveInterval = "فترة الحفظ التلقائي",
            explorer = "المستكشف",
            workspace = "مساحة العمل",
            recents = "الملفات الأخيرة",
            newFile = "ملف جديد",
            newFolder = "مجلد جديد",
            openFile = "فتح ملف",
            folderTree = "شجرة المجلدات",
            createExternalDoc = "ملف خارجي (SAF)",
            support = "الدعم والمساعدة",
            runPreview = "تشغيل / معاينة الكود",
            formatCode = "تنسيق الكود",
            saveFile = "حفظ الملف",
            save = "حفظ",
            cancel = "إلغاء",
            systemLang = "افتراضي النظام",
            englishLang = "الإنجليزية (English)",
            arabicLang = "العربية",
            themeDark = "داكن",
            themeLight = "فاتح",
            themeBlack = "أسود ناصع (AMOLED)",
            themeSystem = "النظام",
            findPlaceholder = "بحث...",
            replacePlaceholder = "استبدال...",
            replace = "استبدال",
            replaceAll = "الكل",
            matchCase = "Aa (حالة الأحرف)",
            wholeWord = "\\b (كلمة كاملة)",
            regex = ".* (تعبير نمطي)",
            previousMatch = "المطابقة السابقة",
            nextMatch = "المطابقة التالية",
            closeSearch = "إغلاق البحث",
            languagesFormatter = "اللغات / المنسق",
            searchLanguagePlaceholder = "ابحث عن لغة أو امتداد (مثل Python, js)...",
            renameFile = "إعادة تسمية الملف",
            deleteFile = "حذف الملف",
            closeTab = "إغلاق التبويب",
            fileProperties = "خصائص الملف",
            goToLine = "الانتقال إلى سطر",
            shortcuts = "اختصارات لوحة المفاتيح",
            line = "سطر",
            col = "عمود",
            saved = "تم الحفظ",
            modified = "معدل",
            terminal = "الطرفية",
            console = "وحدة التحكم",
            preview = "المعاينة",
            splitView = "عرض مقسم",
            clear = "مسح",
            executionCompleted = "اكتمل بنجاح (0)",
            executionError = "خطأ في التشغيل (1)",
            running = "جاري التشغيل...",
            inputPrompt = "أدخل قيمة...",
            sendInput = "إرسال"
        )

        fun forLanguage(langCode: String): AppStrings {
            return when (langCode.lowercase()) {
                "ar" -> Arabic
                "en" -> English
                else -> {
                    val sysLang = Locale.getDefault().language
                    if (sysLang == "ar" || sysLang.startsWith("ar_")) Arabic else English
                }
            }
        }
    }
}

val LocalAppStrings = staticCompositionLocalOf { AppStrings.English }
