package com.example.editor.settings

import androidx.compose.runtime.staticCompositionLocalOf
import java.util.Locale

/**
 * Type-safe, instant-switch localization provider for Arabic and English.
 * Guarantees zero latency and instantaneous recomposition when changing languages.
 */
data class AppStrings(
    val appName: String,
    val settings: String,
    val editor: String,
    val appearance: String,
    val behavior: String,
    val uiLanguage: String,
    val theme: String,
    val fontSize: String,
    val tabSize: String,
    val wordWrap: String,
    val showLineNumbers: String,
    val highlightCurrentLine: String,
    val autoIndent: String,
    val autoCloseBrackets: String,
    val syntaxHighlighting: String,
    val autoSave: String,
    val autoSyncDisk: String,
    val autoSaveInterval: String,
    val explorer: String,
    val workspace: String,
    val recents: String,
    val newFile: String,
    val newFolder: String,
    val openFile: String,
    val folderTree: String,
    val createExternalDoc: String,
    val support: String,
    val runPreview: String,
    val formatCode: String,
    val saveFile: String,
    val save: String,
    val cancel: String,
    val systemLang: String,
    val englishLang: String,
    val arabicLang: String,
    val themeDark: String,
    val themeLight: String,
    val themeBlack: String,
    val themeSystem: String,
    val findPlaceholder: String,
    val replacePlaceholder: String,
    val replace: String,
    val replaceAll: String,
    val matchCase: String,
    val wholeWord: String,
    val regex: String,
    val previousMatch: String,
    val nextMatch: String,
    val closeSearch: String,
    val languagesFormatter: String,
    val searchLanguagePlaceholder: String,
    val renameFile: String,
    val deleteFile: String,
    val closeTab: String,
    val fileProperties: String,
    val goToLine: String,
    val shortcuts: String,
    val line: String,
    val col: String,
    val saved: String,
    val modified: String,
    val terminal: String,
    val console: String,
    val preview: String,
    val splitView: String,
    val clear: String,
    val executionCompleted: String,
    val executionError: String,
    val running: String,
    val inputPrompt: String,
    val sendInput: String,
    // Additional comprehensive UI keys
    val shareCode: String,
    val newExternalFile: String,
    val openDrawer: String,
    val moreOptions: String,
    val noOpenFiles: String,
    val tapPlusToCreate: String,
    val confirmDeleteMessage: String,
    val confirmCloseMessage: String,
    val delete: String,
    val close: String,
    val fileNameLabel: String,
    val folderNameLabel: String,
    val lineNumberLabel: String,
    val autoSaving: String,
    val refresh: String,
    val share: String,
    val properties: String,
    val useSpacesForTab: String,
    val editorFont: String,
    val restoreOpenTabs: String,
    val confirmDelete: String,
    val confirmCloseModified: String,
    val autoSyncDiskToggle: String,
    val autoSaveStorageToggle: String,
    val goToLinePrompt: String,
    val invalidLineNumber: String,
    val goButton: String,
    val createButton: String,
    val fileLabel: String,
    val folderLabel: String,
    val nameCannotBeEmpty: String,
    val nameCannotContainSlash: String,
    val createNewFolder: String,
    val createNewFile: String,
    val closeWithoutSaving: String,
    val unsavedChanges: String,
    val unsavedChangesMessage: String,
    val deleteItemTitle: String,
    val renameItemTitle: String,
    val filePropertiesTitle: String,
    val storageType: String,
    val pathOrUri: String,
    val accessMode: String,
    val readOnly: String,
    val readWrite: String,
    val encoding: String,
    val linesCount: String,
    val charactersCount: String,
    val fileSizeLabel: String,
    val modifiedDate: String,
    val folderIsEmpty: String = "Folder is empty",
    val noRecentFiles: String = "No recent files",
    val consoleIsEmpty: String = "Console is empty",
    val consoleEmptySub: String = "Messages from console.log and errors will appear here",
    val openInExternalBrowser: String = "Open in External Browser",
    val noActiveFileToSave: String = "No open file to save",
    val noActiveFileToFormat: String = "No active file to format",
    val fileSavedSuccess: String = "File saved successfully",
    val codeFormattedSuccess: String = "Code formatted successfully",
    val codeAlreadyFormatted: String = "Already formatted",
    val replacedOccurrences: String = "Replaced %d occurrences",
    val switchLanguage: String = "Switch Language",
    val categoryPopular: String = "Popular",
    val categoryWeb: String = "Web",
    val categoryMobile: String = "Mobile",
    val categoryAll: String = "All",
    val community: String = "Community & Support",
    val communitySubtitle: String = "Connect with the developer on Discord & Telegram",
    val telegramChannel: String = "Telegram",
    val telegramHandle: String = "t.me/EPCD11",
    val discordServer: String = "Discord",
    val discordInvite: String = "discord.gg/FkssmYFY",
    val openLink: String = "Open Link"
) {
    companion object {
        val English = AppStrings(
            appName = "ECODE",
            settings = "Settings",
            editor = "Editor",
            appearance = "Appearance",
            behavior = "Behavior",
            uiLanguage = "UI Language",
            theme = "Theme",
            fontSize = "Font Size",
            tabSize = "Tab Size",
            wordWrap = "Word Wrap",
            showLineNumbers = "Show Line Numbers",
            highlightCurrentLine = "Highlight Active Line",
            autoIndent = "Auto-Indent",
            autoCloseBrackets = "Auto-Close Brackets",
            syntaxHighlighting = "Syntax Highlighting",
            autoSave = "Auto-Save to Local Storage",
            autoSyncDisk = "Auto-Sync to Device Disk",
            autoSaveInterval = "Auto-Save Interval",
            explorer = "Explorer",
            workspace = "Workspace",
            recents = "Recent Files",
            newFile = "New File",
            newFolder = "New Folder",
            openFile = "Open File (SAF)",
            folderTree = "Open Folder Tree (SAF)",
            createExternalDoc = "Create External Document",
            support = "Support & About",
            runPreview = "Run / Preview Code",
            formatCode = "Format Code",
            saveFile = "Save File",
            save = "Save",
            cancel = "Cancel",
            systemLang = "System Default",
            englishLang = "English",
            arabicLang = "العربية (Arabic)",
            themeDark = "Dark",
            themeLight = "Light",
            themeBlack = "Pitch Black (OLED)",
            themeSystem = "System Follow",
            findPlaceholder = "Find in file...",
            replacePlaceholder = "Replace with...",
            replace = "Replace",
            replaceAll = "All",
            matchCase = "Aa (Match Case)",
            wholeWord = "\\b (Whole Word)",
            regex = ".* (Regex)",
            previousMatch = "Previous Match",
            nextMatch = "Next Match",
            closeSearch = "Close Search",
            languagesFormatter = "Languages & Formatter",
            searchLanguagePlaceholder = "Search language (e.g., Python, Kotlin, JS)...",
            renameFile = "Rename File",
            deleteFile = "Delete File",
            closeTab = "Close Tab",
            fileProperties = "File Properties",
            goToLine = "Go to Line",
            shortcuts = "Keyboard Shortcuts",
            line = "Ln",
            col = "Col",
            saved = "Saved",
            modified = "Modified",
            terminal = "Terminal",
            console = "Console",
            preview = "Preview",
            splitView = "Split View",
            clear = "Clear",
            executionCompleted = "Completed (0)",
            executionError = "Error (1)",
            running = "Running...",
            inputPrompt = "Enter input...",
            sendInput = "Send",
            shareCode = "Share Code",
            newExternalFile = "New External File (SAF)",
            openDrawer = "Open Drawer",
            moreOptions = "More Options",
            noOpenFiles = "No open files",
            tapPlusToCreate = "Tap + to create a new file or open from drawer",
            confirmDeleteMessage = "Are you sure you want to delete this item? This action cannot be undone.",
            confirmCloseMessage = "You have unsaved changes. Do you want to close this tab without saving?",
            delete = "Delete",
            close = "Close",
            fileNameLabel = "File Name",
            folderNameLabel = "Folder Name",
            lineNumberLabel = "Line Number",
            autoSaving = "Auto-saving...",
            refresh = "Refresh",
            share = "Share",
            properties = "Properties",
            useSpacesForTab = "Use Spaces for Tab",
            editorFont = "Editor Font",
            restoreOpenTabs = "Restore Open Tabs on Launch",
            confirmDelete = "Confirm Before Delete",
            confirmCloseModified = "Confirm Before Closing Modified",
            autoSyncDiskToggle = "Auto-Sync Changes to File",
            autoSaveStorageToggle = "Auto Save to Local Storage",
            goToLinePrompt = "Enter line number between 1 and %d:",
            invalidLineNumber = "Invalid line number",
            goButton = "Go",
            createButton = "Create",
            fileLabel = "File",
            folderLabel = "Folder",
            nameCannotBeEmpty = "Name cannot be empty",
            nameCannotContainSlash = "Name cannot contain / or \\",
            createNewFolder = "Create New Folder",
            createNewFile = "Create New File",
            closeWithoutSaving = "Don't Save",
            unsavedChanges = "Unsaved Changes",
            unsavedChangesMessage = "The file \"%s\" has unsaved changes. Do you want to save before closing?",
            deleteItemTitle = "Delete Item",
            renameItemTitle = "Rename Item",
            filePropertiesTitle = "File Properties",
            storageType = "Storage",
            pathOrUri = "Path / URI",
            accessMode = "Access Mode",
            readOnly = "Read-Only",
            readWrite = "Read & Write",
            encoding = "Encoding",
            linesCount = "Lines",
            charactersCount = "Characters",
            fileSizeLabel = "Size",
            modifiedDate = "Modified",
            folderIsEmpty = "Folder is empty",
            noRecentFiles = "No recent files",
            consoleIsEmpty = "Console is empty",
            consoleEmptySub = "Messages from console.log and errors will appear here",
            openInExternalBrowser = "Open in External Browser",
            noActiveFileToSave = "No open file to save",
            noActiveFileToFormat = "No active file to format",
            fileSavedSuccess = "File saved successfully",
            codeFormattedSuccess = "Code formatted successfully",
            codeAlreadyFormatted = "Already formatted",
            replacedOccurrences = "Replaced %d occurrences",
            switchLanguage = "Switch Language",
            categoryPopular = "Popular",
            categoryWeb = "Web",
            categoryMobile = "Mobile",
            categoryAll = "All",
            community = "Community & Support",
            communitySubtitle = "Connect with the developer on Discord & Telegram",
            telegramChannel = "Telegram",
            telegramHandle = "t.me/EPCD11",
            discordServer = "Discord",
            discordInvite = "discord.gg/FkssmYFY",
            openLink = "Open Link"
        )

        val Arabic = AppStrings(
            appName = "ECODE",
            settings = "الإعدادات",
            editor = "المحرر",
            appearance = "المظهر",
            behavior = "السلوك",
            uiLanguage = "لغة الواجهة",
            theme = "السمة / المظهر",
            fontSize = "حجم الخط",
            tabSize = "مسافة الجدولة (Tab)",
            wordWrap = "التفاف الكلمات",
            showLineNumbers = "إظهار أرقام الأسطر",
            highlightCurrentLine = "تمييز السطر الحالي",
            autoIndent = "محاذاة تلقائية",
            autoCloseBrackets = "إغلاق الأقواس تلقائيًا",
            syntaxHighlighting = "تلوين الأكواد (Syntax)",
            autoSave = "الحفظ التلقائي في التخزين الداخلي",
            autoSyncDisk = "مزامنة تلقائية مع قرص الجهاز",
            autoSaveInterval = "فترة الحفظ التلقائي",
            explorer = "المستعرض",
            workspace = "مساحة العمل",
            recents = "الملفات الأخيرة",
            newFile = "ملف جديد",
            newFolder = "مجلد جديد",
            openFile = "فتح ملف خارجي (SAF)",
            folderTree = "فتح مجلد خارجي (SAF)",
            createExternalDoc = "إنشاء مستند خارجي",
            support = "الدعم والتواصل",
            runPreview = "تشغيل / معاينة الكود",
            formatCode = "تنسيق الكود",
            saveFile = "حفظ الملف",
            save = "حفظ",
            cancel = "إلغاء",
            systemLang = "لغة النظام التلقائية",
            englishLang = "English",
            arabicLang = "العربية",
            themeDark = "داكن (Dark)",
            themeLight = "فاتح (Light)",
            themeBlack = "أسود نقي (OLED)",
            themeSystem = "حسب النظام",
            findPlaceholder = "البحث في الملف...",
            replacePlaceholder = "استبدال بـ...",
            replace = "استبدال",
            replaceAll = "الكل",
            matchCase = "Aa (حالة الأحرف)",
            wholeWord = "\\b (كلمة كاملة)",
            regex = ".* (تعبير نمطي)",
            previousMatch = "المطابقة السابقة",
            nextMatch = "المطابقة التالية",
            closeSearch = "إغلاق البحث",
            languagesFormatter = "اللغات / المنسق",
            searchLanguagePlaceholder = "ابحث عن لغة أو امتداد (مثل Python, Kotlin, JS)...",
            renameFile = "إعادة تسمية الملف",
            deleteFile = "حذف الملف",
            closeTab = "إغلاق التبويب",
            fileProperties = "خصائص الملف",
            goToLine = "الانتقال إلى سطر",
            shortcuts = "اختصارات لوحة المفاتيح",
            line = "سطر",
            col = "عمود",
            saved = "تم الحفظ",
            modified = "معدل",
            terminal = "الطرفية",
            console = "وحدة التحكم",
            preview = "المعاينة",
            splitView = "عرض مقسم",
            clear = "مسح",
            executionCompleted = "اكتمل بنجاح (0)",
            executionError = "خطأ في التشغيل (1)",
            running = "جاري التشغيل...",
            inputPrompt = "أدخل قيمة...",
            sendInput = "إرسال",
            shareCode = "مشاركة الكود",
            newExternalFile = "ملف خارجي جديد (SAF)",
            openDrawer = "فتح القائمة الجانبية",
            moreOptions = "المزيد من الخيارات",
            noOpenFiles = "لا توجد ملفات مفتوحة",
            tapPlusToCreate = "اضغط على + لإنشاء ملف جديد أو افتح من القائمة الجانبية",
            confirmDeleteMessage = "هل أنت متأكد من حذف هذا العنصر؟ لا يمكن التراجع عن هذا الإجراء.",
            confirmCloseMessage = "توجد تعديلات لم تُحفظ. هل تريد إغلاق التبويب دون حفظ؟",
            delete = "حذف",
            close = "إغلاق",
            fileNameLabel = "اسم الملف",
            folderNameLabel = "اسم المجلد",
            lineNumberLabel = "رقم السطر",
            autoSaving = "جاري الحفظ تلقائيًا...",
            refresh = "تحديث",
            share = "مشاركة",
            properties = "خصائص",
            useSpacesForTab = "استخدام مسافات للتاب",
            editorFont = "نوع خط المحرر",
            restoreOpenTabs = "استعادة التبويبات المفتوحة عند التشغيل",
            confirmDelete = "تأكيد الحذف قبل التنفيذ",
            confirmCloseModified = "تنبيه عند إغلاق ملف معدل",
            autoSyncDiskToggle = "مزامنة التعديلات مع الملف تلقائياً",
            autoSaveStorageToggle = "حفظ تلقائي في التخزين المحلي",
            goToLinePrompt = "أدخل رقم السطر بين 1 و %d:",
            invalidLineNumber = "رقم السطر غير صالح",
            goButton = "انتقال",
            createButton = "إنشاء",
            fileLabel = "ملف",
            folderLabel = "مجلد",
            nameCannotBeEmpty = "الاسم لا يمكن أن يكون فارغاً",
            nameCannotContainSlash = "الاسم لا يمكن أن يحتوي على / أو \\",
            createNewFolder = "إنشاء مجلد جديد",
            createNewFile = "إنشاء ملف جديد",
            closeWithoutSaving = "عدم الحفظ",
            unsavedChanges = "تعديلات غير محفوظة",
            unsavedChangesMessage = "الملف \"%s\" يحتوي على تعديلات غير محفوظة. هل ترغب في حفظها قبل الإغلاق؟",
            deleteItemTitle = "حذف العنصر",
            renameItemTitle = "إعادة تسمية العنصر",
            filePropertiesTitle = "خصائص الملف",
            storageType = "نوع التخزين",
            pathOrUri = "المسار / المعرف",
            accessMode = "وضع الوصول",
            readOnly = "للقراءة فقط",
            readWrite = "قراءة وتعديل",
            encoding = "الترميز",
            linesCount = "عدد الأسطر",
            charactersCount = "عدد الأحرف",
            fileSizeLabel = "الحجم",
            modifiedDate = "تاريخ التعديل",
            folderIsEmpty = "المجلد فارغ",
            noRecentFiles = "لا توجد ملفات أخيرة",
            consoleIsEmpty = "وحدة التحكم فارغة",
            consoleEmptySub = "ستظهر هنا مخرجات console.log والأخطاء البرمجية",
            openInExternalBrowser = "فتح في المتصفح الخارجي",
            noActiveFileToSave = "لا يوجد ملف مفتوح لحفظه",
            noActiveFileToFormat = "لا يوجد ملف مفتوح لتنسيقه",
            fileSavedSuccess = "تم حفظ الملف بنجاح",
            codeFormattedSuccess = "تم تنسيق الكود بنجاح",
            codeAlreadyFormatted = "الكود منسق بالفعل",
            replacedOccurrences = "تم استبدال %d مطابقة",
            switchLanguage = "تغيير لغة البرمجة",
            categoryPopular = "شائع",
            categoryWeb = "ويب",
            categoryMobile = "موبايل",
            categoryAll = "الكل",
            community = "المجتمع والدعم",
            communitySubtitle = "تواصل مع المطور مباشرة عبر ديسكورد وتيلغرام",
            telegramChannel = "تيلغرام",
            telegramHandle = "t.me/EPCD11",
            discordServer = "ديسكورد",
            discordInvite = "discord.gg/FkssmYFY",
            openLink = "فتح الرابط"
        )

        fun forLanguage(langCode: String): AppStrings {
            return when (langCode.lowercase()) {
                "ar" -> Arabic
                "en" -> English
                else -> {
                    if (LocaleHelper.isSystemArabic()) Arabic else English
                }
            }
        }
    }
}

val LocalAppStrings = staticCompositionLocalOf { AppStrings.English }
